"""feature-cli-ergonomics §8：shell 补全、run / path、每账号环境变量。"""

import io
import json
import os
import shlex
import shutil
import stat
import subprocess
import sys
import unittest
from contextlib import redirect_stderr, redirect_stdout
from unittest import mock

from helpers import SRC, CliTestCase

sys.path.insert(0, SRC)

from multi_codex import cli, launcher  # noqa: E402

# v0.3.0（493818f）的 launcher.render 输出：没有环境变量时，新版本必须与它逐字节相同。
V030_HTTP = (
    '#!/bin/sh\n# managed-by: multi-codex account=work\n# Generated by multi-codex. Do not edit; use '
    '`multi-codex proxy` or `multi-codex apply`.\naccount_dir=/HOME/.cx/work\nif [ ! -d "$account_dir" ]; then\n'
    '  printf \'multi-codex: account directory does not exist: %s\\n\' "$account_dir" >&2\n  exit 1\nfi\n'
    'CODEX_HOME="$account_dir"\nexport CODEX_HOME\nHTTPS_PROXY=http://127.0.0.1:7901; HTTP_PROXY=http://127.0.0.1:7901;'
    ' https_proxy=http://127.0.0.1:7901; http_proxy=http://127.0.0.1:7901\nexport HTTPS_PROXY HTTP_PROXY https_proxy '
    'http_proxy\nunset ALL_PROXY all_proxy\nNO_PROXY="${NO_PROXY:+$NO_PROXY,}localhost,127.0.0.1,::1"\n'
    'no_proxy="${no_proxy:+$no_proxy,}localhost,127.0.0.1,::1"\nexport NO_PROXY no_proxy\n'
    'if ! command -v codex >/dev/null 2>&1; then\n  echo "multi-codex: codex not found in PATH" >&2\n  exit 127\n'
    'fi\nexec codex "$@"\n')
V030_OFF = (
    '#!/bin/sh\n# managed-by: multi-codex account=work\n# Generated by multi-codex. Do not edit; use '
    '`multi-codex proxy` or `multi-codex apply`.\naccount_dir=/HOME/.cx/work\nif [ ! -d "$account_dir" ]; then\n'
    '  printf \'multi-codex: account directory does not exist: %s\\n\' "$account_dir" >&2\n  exit 1\nfi\n'
    'CODEX_HOME="$account_dir"\nexport CODEX_HOME\nunset HTTPS_PROXY HTTP_PROXY ALL_PROXY NO_PROXY https_proxy '
    'http_proxy all_proxy no_proxy\nif ! command -v codex >/dev/null 2>&1; then\n'
    '  echo "multi-codex: codex not found in PATH" >&2\n  exit 127\nfi\nexec codex "$@"\n')

# 比较两次运行看到的环境时要排除：shell 自己维护的变量，以及 macOS 给经 Python 启动的进程注入的
# __CF_USER_TEXT_ENCODING（run 经过 python 再 exec，直接运行启动命令则不经过）。
SHELL_VARS = {"_", "SHLVL", "PWD", "OLDPWD", "__CF_USER_TEXT_ENCODING"}


class ErgonomicsBase(CliTestCase):
    def launcher_file(self, name):
        return os.path.join(self.bin, "codex-" + name)

    def mode(self, path):
        return stat.S_IMODE(os.stat(path).st_mode)


class CompletionTest(ErgonomicsBase):
    def setUp(self):
        super().setUp()
        # 补全脚本按 Tab 时会调用 multi-codex completion --list-accounts，PATH 上要有这个命令。
        self.write(os.path.join(self.fakebin, "multi-codex"),
                   '#!/bin/sh\nexec "$FAKE_PYTHON" -m multi_codex "$@"\n', 0o755)
        for name in ("jakoes.wu@icloud.com", "jakoes.wu@gmail.com", "work"):
            self.ok("add", name)

    def bash_complete(self, line):
        script = self.ok("completion", "bash").out
        # 补全脚本里有大括号，不能整体走 str.format。
        driver = (script + "\nCOMP_LINE=" + shlex.quote(line) + "\nCOMP_POINT=${#COMP_LINE}\nCOMP_WORDS=()\n"
                  "COMP_CWORD=0\n_multi_codex\nprintf '%s\\n' \"${COMPREPLY[@]}\"\n")
        proc = subprocess.run(["bash", "--norc", "--noprofile", "-c", driver], env=self.env,
                              stdout=subprocess.PIPE, stderr=subprocess.PIPE, universal_newlines=True)
        self.assertEqual(proc.returncode, 0, proc.stderr)
        return [item for item in proc.stdout.splitlines() if item]

    def test_scripts_generate(self):
        for shell in ("bash", "zsh", "fish"):
            with self.subTest(shell=shell):
                out = self.ok("completion", shell).out
                self.assertIn("doctor", out)
                self.assertIn("live", out)

    def test_bash_cases(self):
        self.assertIn("doctor", self.bash_complete("multi-codex "))
        self.assertEqual(sorted(self.bash_complete("multi-codex run jak")),
                         ["jakoes.wu@gmail.com", "jakoes.wu@icloud.com"])
        self.assertEqual(self.bash_complete("multi-codex run jakoes.wu@ic"), ["icloud.com"])
        self.assertEqual(sorted(self.bash_complete("multi-codex proxy jakoes.wu@icloud.com ")), ["inherit", "off"])
        self.assertIn("work", self.bash_complete("multi-codex migrate-default --source /x "))
        self.assertEqual(self.bash_complete("multi-codex usage --l"), ["--live"])
        self.assertEqual(self.bash_complete("multi-codex run work -- "), [])

    @unittest.skipUnless(shutil.which("zsh"), "zsh is not installed")
    def test_zsh_syntax(self):
        script = os.path.join(self.tmp, "c.zsh")
        self.write(script, self.ok("completion", "zsh").out)
        self.assertEqual(subprocess.run(["zsh", "-n", script]).returncode, 0)

    @unittest.skipUnless(shutil.which("fish"), "fish is not installed")
    def test_fish_syntax(self):
        script = os.path.join(self.tmp, "c.fish")
        self.write(script, self.ok("completion", "fish").out)
        self.assertEqual(subprocess.run(["fish", "--no-execute", script]).returncode, 0)

    def test_list_accounts(self):
        result = self.ok("completion", "--list-accounts")
        self.assertEqual(result.out.split(), ["jakoes.wu@icloud.com", "jakoes.wu@gmail.com", "work"])
        self.write(os.path.join(self.state, "config.json"), "{broken")
        result = self.ok("completion", "--list-accounts")
        self.assertEqual((result.out, result.err), ("", ""))
        self.assertEqual(self.run_cli("completion").code, 2)


class RunPathTest(ErgonomicsBase):
    def setUp(self):
        super().setUp()
        self.ok("add", "work", "--proxy", "7901")
        self.ok("env", "work", "FOO=bar")

    def test_run_command_sees_account_environment(self):
        result = self.run_cli("run", "work", "--", "sh", "-c",
                              'echo "$CODEX_HOME|$HTTPS_PROXY|$FOO|${MULTI_CODEX_RUN_SCRIPT-unset}"')
        self.assertEqual(result.code, 0, result)
        self.assertEqual(result.out.strip(),
                         "{}|http://127.0.0.1:7901|bar|unset".format(os.path.join(self.root, "work")))
        self.assertEqual(self.run_cli("run", "work", "--", "sh", "-c", "exit 7").code, 7)

    def test_run_codex_matches_launcher(self):
        self.assertEqual(self.run_cli("run", "work").code, 0)
        with open(self.fake_out + ".args") as handle:
            run_args = handle.read()
        with open(self.fake_out + ".env") as handle:
            run_env = dict(line.split("=", 1) for line in handle.read().splitlines() if "=" in line)
        _, _, launcher_env, _ = self.run_launcher("work")
        with open(self.fake_out + ".args") as handle:
            # 两种方式都不带参数运行 codex，假 codex 记录下的参数应完全相同。
            self.assertEqual(run_args, handle.read())
        strip = lambda env: {k: v for k, v in env.items() if k not in SHELL_VARS}  # noqa: E731
        self.assertEqual(strip(run_env), strip(launcher_env))

    def test_run_errors(self):
        self.assertEqual(self.run_cli("run", "ghost").code, 1)
        self.assertEqual(self.run_cli("run", "work", "--", "no-such-command-xyz").code, 127)
        self.assertEqual(self.run_cli("run", "work", "extra").code, 2)
        result = self.run_cli("run", "work", "--", "--", "-c", "true")
        self.assertEqual(result.code, 127, result)  # 第二个 -- 原样当作命令名
        os.rename(os.path.join(self.root, "work"), os.path.join(self.tmp, "moved"))
        self.assertEqual(self.run_cli("run", "work", "--", "true").code, 1)

    def test_secret_not_in_argv(self):
        captured = {}

        def fake_execve(path, argv, env):
            captured.update(path=path, argv=argv, env=env)
            raise SystemExit(0)

        patcher = mock.patch.dict(os.environ, self.env, clear=False)
        patcher.start()
        self.addCleanup(patcher.stop)
        os.environ.pop("XDG_CONFIG_HOME", None)
        with mock.patch.object(cli.os, "execve", fake_execve), redirect_stdout(io.StringIO()), \
                redirect_stderr(io.StringIO()):
            with self.assertRaises(SystemExit):
                cli.main(["run", "work", "--", "true"])
        self.assertNotIn("bar", " ".join(captured["argv"]))
        self.assertIn("FOO=bar", captured["env"][launcher.RUN_SCRIPT_ENV])

    def test_path(self):
        result = self.ok("path", "work")
        self.assertEqual(result.out.strip(), os.path.join(self.root, "work"))
        self.assertEqual(self.run_cli("path", "ghost").code, 1)


class EnvTest(ErgonomicsBase):
    def setUp(self):
        super().setUp()
        self.ok("add", "work")

    def test_no_env_launcher_identical_to_v030(self):
        self.assertEqual(launcher.render("work", "/HOME/.cx/work", "http://127.0.0.1:7901"), V030_HTTP)
        self.assertEqual(launcher.render("work", "/HOME/.cx/work", "off", {}), V030_OFF)
        self.assertEqual(self.mode(self.launcher_file("work")), 0o755)

    def test_v030_config_converges_without_changes(self):
        config = os.path.join(self.state, "config.json")
        with open(config) as handle:
            data = json.load(handle)
        self.assertNotIn("env", data["accounts"]["work"])
        with open(config, "rb") as handle:
            before = handle.read()
        result = self.ok("apply")
        self.assertNotIn("update", result.out)
        with open(config, "rb") as handle:
            self.assertEqual(before, handle.read())

    def test_set_unset_clear(self):
        self.ok("env", "work", "FOO=bar", "B=a b$c")
        path = self.launcher_file("work")
        self.assertEqual(self.mode(path), 0o700)
        _, _, seen, _ = self.run_launcher("work")
        self.assertEqual((seen["FOO"], seen["B"]), ("bar", "a b$c"))
        self.assertEqual(self.ok("env", "work").out, "B=a b$c\nFOO=bar\n")
        self.ok("env", "work", "--unset", "FOO")
        _, _, seen, _ = self.run_launcher("work")
        self.assertNotIn("FOO", seen)
        self.ok("env", "work", "--clear")
        self.assertEqual(self.mode(path), 0o755)
        with open(path) as handle:
            self.assertNotIn("export B", handle.read())

    def test_invalid_keys(self):
        before = self.snapshot()
        for args in (("CODEX_HOME=x",), ("HTTPS_PROXY=x",), ("1A=x",), ("A=1", "--unset", "A"),
                     ("A=1", "--clear"), ("noequals",)):
            with self.subTest(args=args):
                self.assertEqual(self.run_cli("env", "work", *args).code, 2)
        self.assertEqual(before, self.snapshot())
        bad = os.path.join(self.tmp, "bad.json")
        self.write(bad, json.dumps({"version": 1, "accounts": {"work": {"env": {"CODEX_HOME": "x"}}}}))
        self.assertEqual(self.run_cli("apply", "-f", bad).code, 1)

    def test_permissions(self):
        path = self.launcher_file("work")
        os.chmod(path, 0o775)
        self.assertIn(" ok", self.ok("list").out.splitlines()[-1])
        self.assertNotIn("update launcher", self.ok("apply").out)
        self.ok("env", "work", "K=v")
        os.chmod(path, 0o755)
        self.assertIn("stale", self.ok("list").out)
        self.ok("apply")
        self.assertEqual(self.mode(path), 0o700)

    def test_key_order_in_apply_file(self):
        self.ok("env", "work", "A=1", "B=2")
        spec = os.path.join(self.tmp, "spec.json")
        self.write(spec, json.dumps({"version": 1, "accounts": {"work": {"env": {"B": "2", "A": "1"}}}}))
        result = self.ok("apply", "-f", spec, "-v")
        self.assertIn("unchanged config", result.out)

    def test_dry_run_and_migration_block(self):
        before = self.snapshot()
        self.assertEqual(self.run_cli("env", "work", "FOO=bar", "--dry-run").code, 0)
        self.assertEqual(before, self.snapshot())
        self.write(os.path.join(self.state, "migrate-journal.json"),
                   json.dumps({"name": "m", "source": "/s", "target": "/t", "backup": "/b", "mode": "rename",
                               "phase": "moved"}))
        self.assertEqual(self.run_cli("env", "work", "FOO=bar").code, 1)
        self.assertEqual(self.run_cli("env", "work").code, 0)

    def test_list_without_lock(self):
        self.ok("env", "work", "FOO=bar")
        holder = subprocess.Popen([sys.executable, "-c",
                                   "import sys,time; sys.path.insert(0, {!r}); "
                                   "from multi_codex.lock import WriteLock\n"
                                   "with WriteLock():\n    print('locked', flush=True); time.sleep(30)".format(SRC)],
                                  env=self.env, stdout=subprocess.PIPE, universal_newlines=True)
        self.addCleanup(lambda: (holder.kill(), holder.wait(), holder.stdout.close()))
        self.assertEqual(holder.stdout.readline().strip(), "locked")
        self.assertEqual(self.ok("env", "work").out, "FOO=bar\n")
        self.assertEqual(self.run_cli("env", "work", "X=1").code, 1)  # 写操作要锁

    def test_list_json_and_doctor(self):
        self.ok("env", "work", "SECRET_TOKEN=sk-value")
        result = self.ok("list", "--json")
        self.assertEqual(json.loads(result.out)["accounts"][0]["env_keys"], ["SECRET_TOKEN"])
        self.assertNotIn("sk-value", result.out)
        checks = {c["id"]: c for c in json.loads(self.run_cli("doctor", "--json").out)["checks"]}
        self.assertEqual(checks["drift"]["status"], "ok")


if __name__ == "__main__":
    unittest.main()
