"""启动命令 `<bin_dir>/codex-<名称>` 的生成与识别。

启动命令是由 config.json 推导出的产物，内容完全由 (账号名, 账号目录, 代理) 决定，
所以“内容相同即 unchanged”就是幂等判断。第 2 行的受管标记用来区分本工具生成的文件
和用户自己的同名文件：没有标记的文件一律不覆盖、不删除。
"""

import os
import shlex
from typing import Dict, Optional

from .config import PROXY_INHERIT, PROXY_OFF, is_socks
from .fsutil import KIND_FILE, entry_kind, read_text

MARKER_PREFIX = "# managed-by: multi-codex account="
LAUNCHER_PREFIX = "codex-"
LAUNCHER_MODE = 0o755

_PROXY_VARS = ("HTTPS_PROXY", "HTTP_PROXY", "ALL_PROXY", "NO_PROXY",
               "https_proxy", "http_proxy", "all_proxy", "no_proxy")
_NO_PROXY_HOSTS = "localhost,127.0.0.1,::1"


def launcher_path(bin_dir: str, name: str) -> str:
    return os.path.join(bin_dir, LAUNCHER_PREFIX + name)


def render(name: str, account_dir: str, proxy: str) -> str:
    """生成 POSIX sh 启动命令的完整内容。所有值都经 shlex.quote 转义。"""
    q_dir = shlex.quote(account_dir)
    lines = [
        "#!/bin/sh",
        MARKER_PREFIX + name,
        "# Generated by multi-codex. Do not edit; use `multi-codex proxy` or `multi-codex apply`.",
        "account_dir=" + q_dir,
        # codex 遇到不存在的 CODEX_HOME 只会给出难懂的配置错误，这里提前给出明确提示。
        'if [ ! -d "$account_dir" ]; then',
        # 用 printf 而不是 echo：dash 的 echo 会解释路径里的反斜杠。
        '  printf \'multi-codex: account directory does not exist: %s\\n\' "$account_dir" >&2',
        "  exit 1",
        "fi",
        'CODEX_HOME="$account_dir"',
        "export CODEX_HOME",
    ]
    lines.extend(_proxy_lines(proxy))
    lines.extend([
        "if ! command -v codex >/dev/null 2>&1; then",
        '  echo "multi-codex: codex not found in PATH" >&2',
        "  exit 127",
        "fi",
        'exec codex "$@"',
        "",
    ])
    return "\n".join(lines)


def _proxy_lines(proxy: str) -> list:
    if proxy == PROXY_INHERIT:
        # 不动任何代理变量，沿用启动时 shell 里的值。
        return []
    if proxy == PROXY_OFF:
        # 清掉全部 8 个变量；只是“不导出”挡不住从父进程继承来的代理。
        return ["unset " + " ".join(_PROXY_VARS)]
    q_proxy = shlex.quote(proxy)
    lines = [
        "HTTPS_PROXY={0}; HTTP_PROXY={0}; https_proxy={0}; http_proxy={0}".format(q_proxy),
        "export HTTPS_PROXY HTTP_PROXY https_proxy http_proxy",
    ]
    if is_socks(proxy):
        lines.append("ALL_PROXY={0}; all_proxy={0}; export ALL_PROXY all_proxy".format(q_proxy))
    else:
        # http 代理不写 ALL_PROXY：curl 等程序会把它用于所有协议。同时清掉继承来的值，
        # 否则父进程里的另一个 ALL_PROXY 可能把部分流量带到别的代理上。
        lines.append("unset ALL_PROXY all_proxy")
    # 在用户原有的 NO_PROXY 后追加本地地址，不覆盖用户原来的内网例外；原值为空时不留前导逗号。
    lines.append('NO_PROXY="${{NO_PROXY:+$NO_PROXY,}}{}"'.format(_NO_PROXY_HOSTS))
    lines.append('no_proxy="${{no_proxy:+$no_proxy,}}{}"'.format(_NO_PROXY_HOSTS))
    lines.append("export NO_PROXY no_proxy")
    return lines


def managed_account(path: str) -> Optional[str]:
    """若 path 是本工具生成的启动命令，返回其中记录的账号名；否则返回 None。

    只认普通文件：软链、目录或读不出文本的文件都视为“不归本工具管理”。
    """
    if entry_kind(path) != KIND_FILE:
        return None
    content = read_text(path)
    if content is None:
        return None
    lines = content.split("\n", 2)
    if len(lines) < 2 or not lines[1].startswith(MARKER_PREFIX):
        return None
    return lines[1][len(MARKER_PREFIX):].strip() or None


def scan_managed(bin_dir: str) -> Dict[str, str]:
    """列出 bin_dir 中所有受管启动命令，返回 {账号名: 路径}。bin_dir 不存在时返回空。"""
    found: Dict[str, str] = {}
    try:
        names = os.listdir(bin_dir)
    except OSError:
        return found
    for entry in sorted(names):
        if not entry.startswith(LAUNCHER_PREFIX):
            continue
        path = os.path.join(bin_dir, entry)
        account = managed_account(path)
        if account is not None:
            found[account] = path
    return found
