"""按目录绑定自动选账号的入口命令 `<bin_dir>/codex-auto`（feature-auto-launcher）。

入口与账号启动命令一样是由 config.json 推导出的产物：有目录绑定时由收敛计划（accounts.plan）生成，
没有绑定时删除。它只负责选账号，再用绝对路径 exec 该账号的 `codex-<名称>`；代理、隔离变量与
环境变量都由账号启动命令负责，入口本身不设置任何环境。

选账号的规则必须与 binding.resolve（`multi-codex run` 省略账号名时）完全一致：从当前目录向上找最近的绑定；
最近的绑定指向未登记账号时报错退出 1，不继续向上找；一条都没有时运行普通 codex（默认账号）。
"""

import os
import shlex
from typing import List

from . import launcher
from .config import Config
from .fsutil import KIND_FILE, entry_kind, expand, read_text

ROUTER_NAME = "auto"
# 不以 launcher.MARKER_PREFIX（`… account=`）开头：managed_account 对入口返回 None，
# 孤儿清理与 restore 的残留清理都不会把它当成账号启动命令。
ROUTER_MARKER = "# managed-by: multi-codex router"
ROUTER_MODE = 0o755  # 入口不含任何密钥，所有人可读


def router_path(bin_dir: str) -> str:
    return launcher.launcher_path(bin_dir, ROUTER_NAME)


def is_router(path: str) -> bool:
    """path 是否是本工具生成的入口：只认普通文件，第 2 行必须完全等于标记（同 launcher.managed_account）。"""
    if entry_kind(path) != KIND_FILE:
        return False
    content = read_text(path)
    if content is None:
        return False
    lines = content.split("\n", 2)
    return len(lines) >= 2 and lines[1] == ROUTER_MARKER


def render(config: Config) -> str:
    """生成入口脚本。键是 binding.normalize_dir 得到的物理路径，按字典序输出，内容稳定。

    当前目录必须用外部命令 /bin/pwd -P 取：macOS 的 /bin/sh（bash）内建 pwd -P 按继承来的 $PWD 逐段解析，
    用户换了大小写 cd 进来时会保留输入的大小写，与绑定键（磁盘上的真实大小写）对不上，账号会悄悄选错。

    每段的长度用 Python 算好写成字面数字：多条命中时取最长的键，等价于 resolve 的“最近祖先”；
    不在 sh 里用 ${#var}，它对多字节字符按字节还是按字符计在不同 shell 里不一致。
    """
    bin_dir = expand(config.bin_dir)
    lines: List[str] = [
        "#!/bin/sh",
        ROUTER_MARKER,
        "# Generated by multi-codex from directory bindings. Do not edit; use `multi-codex bind` / `unbind`.",
        "here=$(/bin/pwd -P 2>/dev/null || pwd -P) || exit 1",
        "best=0",
        "target=''",
        "stale=''",
    ]
    for key in sorted(config.bindings):
        name = config.bindings[key]
        account = config.find(name)
        if account is not None:
            assign = "target={}; stale=''".format(shlex.quote(launcher.launcher_path(bin_dir, account.name)))
        else:
            # 悬空绑定：与 cmd_run 同样报错退出。文字里不放反引号和 $：单引号里出现它们会触发 shellcheck SC2016。
            message = "account {} bound to {} is not registered; run: multi-codex unbind {}".format(name, key, key)
            assign = "target=''; stale={}".format(shlex.quote(message))
        length = len(key)
        update = 'if [ {0} -gt "$best" ]; then best={0}; {1}; fi'.format(length, assign)
        if key == "/":
            # "$here/" 永远以 "/" 开头；写成 case 模式会变成 "//"*，匹配不上，所以根目录无条件命中。
            lines.append(update)
            continue
        lines.extend([
            'case "$here/" in',
            "  {}/*)".format(shlex.quote(key)),
            "    {} ;;".format(update),
            "esac",
        ])
    lines.extend([
        'if [ -n "$stale" ]; then',
        "  printf 'multi-codex: %s\\n' \"$stale\" >&2",
        "  exit 1",
        "fi",
        'if [ -n "$target" ]; then',
        '  if [ ! -x "$target" ]; then',
        "    printf 'multi-codex: launcher %s is missing; run multi-codex apply\\n' \"$target\" >&2",
        "    exit 1",
        "  fi",
        '  exec "$target" "$@"',
        "fi",
        "printf 'multi-codex: no account is bound to %s or its parents; running codex (the default account)\\n' "
        '"$here" >&2',
        "if ! command -v codex >/dev/null 2>&1; then",
        '  echo "multi-codex: codex not found in PATH" >&2',
        "  exit 127",
        "fi",
        'exec codex "$@"',
        "",
    ])
    return "\n".join(lines)


def same_file(path: str, others) -> bool:
    """path 与 others 中任一路径是否是同一个文件（按 st_dev / st_ino）。

    计划里判断“入口位置上的文件是否正要被删”只能按文件身份：macOS 上 codex-Auto 与 codex-auto 是同一个文件，
    字符串却不同；按 casefold 比较文件名又会在区分大小写的 Linux 上把用户自己的 codex-auto 误当成要删的文件。
    """
    try:
        target = os.lstat(path)
    except OSError:
        return False
    for other in others:
        try:
            if os.path.samestat(target, os.lstat(other)):
                return True
        except OSError:
            continue
    return False
